######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 5 21:59:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += breakout.h breakout_canvas.h
SOURCES += breakout.cpp breakout_canvas.cpp main.cpp
