######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 17 15:00:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pong.h pong_canvas.h
SOURCES += main.cpp pong.cpp pong_canvas.cpp
