######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 16 16:56:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += mainwindow.h user.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp user.cpp
